---
# tasks file for vector
  - name: Install epel-release
    become: true
    ansible.builtin.yum:
      name: epel-release
      state: present
  - name: NGINX | Install Nginx
    become: true
    ansible.builtin.yum:
      name: nginx
      state: present
    notify: Start nginx
  - name: NGINX | Create general config
    become: true
    ansible.builtin.template:
      src: templates/nginx.conf
      dest: /etc/nginx/nginx.conf
      mode: 0644
    notify: Reload nginx
  - name: Get vector distrib
    ansible.builtin.get_url:
      url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
      dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
  - name: Install vector package
    become: true
    ansible.builtin.yum:
      name:
        - vector-{{ vector_version }}-1.x86_64.rpm
    notify: Start vector service
